export const quotes = {
    bg: [
        { text: "Умът е всичко. Каквото мислиш, това ставаш.", author: "Буда" },
        { text: "Хиляди свещи могат да бъдат запалени от една единствена свещ, и животът на свещта няма да бъде съкратен. Щастието никога не намалява, като се споделя.", author: "Буда" },
        { text: "Няма път към щастието. Щастието е самият път.", author: "Буда" },
        { text: "Не се плаши от бавния растеж, плаши се само от застоя.", author: "Китайска поговорка" },
        { text: "Този, който премества планина, започва като носи малки камъни.", author: "Конфуций" },
        { text: "Най-доброто време да засадиш дърво беше преди 20 години. Второто най-добро време е сега.", author: "Китайска поговорка" },
        { text: "Провалът не е падане, а отказът да се изправиш отново.", author: "Китайска поговорка" },
        { text: "Всичко, което сме, е резултат от това, което сме мислили.", author: "Буда" },
        { text: "Три нещата не могат да бъдат скрити задълго: слънцето, луната и истината.", author: "Буда" },
        { text: "По-добре да победиш себе си, отколкото да спечелиш хиляди битки.", author: "Буда" },
        { text: "Който гледа навън, сънува; който гледа навътре, се пробужда.", author: "Карл Юнг" },
        { text: "Познай себе си.", author: "Сократ" },
        { text: "Единствената истинска мъдрост е да знаеш, че нищо не знаеш.", author: "Сократ" },
        { text: "Животът е това, което се случва, докато правим други планове.", author: "Джон Ленън" },
        { text: "Бъди промяната, която искаш да видиш в света.", author: "Махатма Ганди" },
        { text: "Слабият никога не може да прости. Прошката е атрибут на силния.", author: "Махатма Ганди" },
        { text: "Бъдещето зависи от това, което правиш днес.", author: "Махатма Ганди" },
        { text: "Успехът е да вървиш от провал към провал, без да губиш ентусиазъм.", author: "Уинстън Чърчил" },
        { text: "Ако минаваш през ада, продължавай да вървиш.", author: "Уинстън Чърчил" },
        { text: "Никога, никога, никога не се предавай.", author: "Уинстън Чърчил" },
        { text: "Начинът да започнеш е да спреш да говориш и да започнеш да правиш.", author: "Уолт Дисни" },
        { text: "Всички наши мечти могат да се сбъднат, ако имаме куража да ги преследваме.", author: "Уолт Дисни" },
        { text: "Не е важно колко бавно вървиш, стига да не спираш.", author: "Конфуций" },
        { text: "Нашите животи започват да свършват в деня, в който замълчим за нещата, които имат значение.", author: "Мартин Лутър Кинг" },
        { text: "Вярвай, че можеш, и си изминал половината път.", author: "Теодор Рузвелт" },
        { text: "Прави каквото можеш, с това което имаш, там където си.", author: "Теодор Рузвелт" },
        { text: "Възможностите не идват сами. Ти ги създаваш.", author: "Крис Гросър" },
        { text: "Не чакай. Времето никога няма да е точно.", author: "Наполеон Хил" },
        { text: "Всичко, което умът може да повярва и да зачене, може и да го постигне.", author: "Наполеон Хил" },
        { text: "Трудностите често подготвят обикновените хора за необикновена съдба.", author: "К.С. Луис" },
        { text: "Никога не си твърде стар, за да си поставиш нова цел или да мечтаеш нова мечта.", author: "К.С. Луис" },
        { text: "Единственият начин да вършиш страхотна работа е да обичаш това, което правиш.", author: "Стив Джобс" },
        { text: "Всичко изглежда невъзможно, докато не бъде направено.", author: "Нелсън Мандела" },
        { text: "Не ме съди по успехите ми, съди ме по това колко пъти съм падал и съм ставал отново.", author: "Нелсън Мандела" },
        { text: "Животът е или дръзко приключение, или нищо.", author: "Хелън Келър" },
        { text: "Оптимизмът е вярата, която води до постижения.", author: "Хелън Келър" },
        { text: "Най-добрият начин да предскажеш бъдещето е да го създадеш.", author: "Питър Дракър" },
        { text: "Ако искаш да летиш, трябва да се освободиш от нещата, които те тежат.", author: "Тони Морисън" },
        { text: "Дисциплината е мостът между целите и постиженията.", author: "Джим Рон" },
        { text: "Мотивацията е това, което те кара да започнеш. Навикът е това, което те поддържа.", author: "Джим Рон" },
        { text: "Успешните хора правят това, което неуспешните не искат да правят.", author: "Джим Рон" },
        { text: "Всеки ден е ново начало. Поеми дълбоко дъх и започни отново.", author: "Неизвестен" },
        { text: "Не позволявай на вчерашния ден да заема твърде много от днешния.", author: "Уил Роджърс" },
        { text: "Учи се от вчера, живей за днес, надей се за утре.", author: "Алберт Айнщайн" },
        { text: "В средата на трудността лежи възможността.", author: "Алберт Айнщайн" },
        { text: "Логиката ще те отведе от А до Б. Въображението ще те отведе навсякъде.", author: "Алберт Айнщайн" },
        { text: "Тайната на успеха е постоянството в целта.", author: "Бенджамин Дизраели" },
        { text: "Действието е основният ключ към всеки успех.", author: "Пабло Пикасо" },
        { text: "Смисълът на живота е да откриеш своята дарба. Целта на живота е да я споделиш.", author: "Пабло Пикасо" },
        { text: "Можеш, само ако мислиш, че можеш.", author: "Джордж Рийвс" },
        { text: "Късметът е това, което се случва, когато подготовката срещне възможността.", author: "Сенека" },
        { text: "Не е нужно да си велик, за да започнеш, но трябва да започнеш, за да станеш велик.", author: "Зиг Зиглар" }
    ],
    en: [
        { text: "The mind is everything. What you think you become.", author: "Buddha" },
        { text: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha" },
        { text: "There is no path to happiness. Happiness is the path.", author: "Buddha" },
        { text: "Be not afraid of growing slowly, be afraid only of standing still.", author: "Chinese Proverb" },
        { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
        { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
        { text: "Failure is not falling down but refusing to get up.", author: "Chinese Proverb" },
        { text: "What we are is the result of what we have thought.", author: "Buddha" },
        { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
        { text: "It is better to conquer yourself than to win a thousand battles.", author: "Buddha" },
        { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
        { text: "Know thyself.", author: "Socrates" },
        { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
        { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon" },
        { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
        { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
        { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
        { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
        { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
        { text: "Never, never, never give up.", author: "Winston Churchill" },
        { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
        { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
        { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
        { text: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
        { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
        { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
        { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
        { text: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
        { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
        { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
        { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
        { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
        { text: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", author: "Nelson Mandela" },
        { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
        { text: "Optimism is the faith that leads to achievement.", author: "Helen Keller" },
        { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
        { text: "If you wanna fly, you got to give up the shit that weighs you down.", author: "Toni Morrison" },
        { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
        { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn" },
        { text: "Successful people do what unsuccessful people are not willing to do.", author: "Jim Rohn" },
        { text: "Every day is a new beginning. Take a deep breath and start again.", author: "Unknown" },
        { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
        { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
        { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
        { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
        { text: "The secret of success is constancy to purpose.", author: "Benjamin Disraeli" },
        { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
        { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
        { text: "You can if you think you can.", author: "George Reeves" },
        { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
        { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" }
    ]
};
